### ISSUE TITLE
Wrong roles for states. PLease fix

### ISSUE THREAD

**Issue by GermanBluefox** [schmupu/ioBroker.sia#1]
There is a rather clear schema for roles of states.
As I can see from here https://github.com/schmupu/ioBroker.sia/blob/master/lib/datapoints.js#L5
Roles defined wrong.
"value" cannot have a type "string" (only "number").

Can this state have type "number"? https://github.com/schmupu/ioBroker.sia/blob/master/lib/datapoints.js#L12

"Timestamp" has a role "date" or "value.time", depends on type of variable: "string" or "number".

Check the roles here: https://github.com/ioBroker/ioBroker/blob/master/doc/STATE_ROLES.md

**Comment by schmupu** [comment]
Thanx, now I got it. I will fix it tomorrow.

**Comment by schmupu** [comment]
Definition of roles described in the ioBroker documentation for states.
