### ISSUE TITLE
Required SIA Fields missing

### ISSUE THREAD

**Issue by paulsidler4823** [schmupu/ioBroker.sia#17]
Hi, 

I am working on an R&D project where i want to receive SIA messages in ioBroker and run a Node-RED workflow based on the message in the SIA message. 

Because I don't have the hardware yet that will send out SIA messages, i would like to get it started with examples generated on http://s545463982.onlinehome.us/DC09Gen/

But they don't work; I have a "Required SIA Fields missing" message each time. Am I doing something wrong? Please see the screenshots attached. Any help is welcome! Thanks. 

Paul

<img width="1537" alt="Schermafbeelding 2020-03-02 om 15 14 35" src="https://user-images.githubusercontent.com/60177309/75684672-89cebb00-5c99-11ea-80d7-4cceccf08d9e.png">

<img width="861" alt="Schermafbeelding 2020-03-02 om 15 14 57" src="https://user-images.githubusercontent.com/60177309/75684685-8f2c0580-5c99-11ea-89f3-d5838eb44f3e.png">

<img width="1743" alt="Schermafbeelding 2020-03-02 om 15 15 35" src="https://user-images.githubusercontent.com/60177309/75684696-92bf8c80-5c99-11ea-8c56-01f58abea89d.png">

**Comment by schmupu** [comment]
The SIA DC09 protocol is very old 👎 and it is a mix of ASCII and HEX data. You can find the specification here : https://www.yumpu.com/en/document/view/47594214/dc-09-preparing-for-ansi-public-review-security-industry-
