### ISSUE TITLE
Having trouble communicating via SIA

### ISSUE THREAD

**Issue by skitzo2000** [schmupu/ioBroker.sia#3]
What encoding should messages be sent in?  I'm attempting to recreate the SIA sending method via php.  I'm sending the data as a string, but all I ever get in the log is:  Required SIA fields missing

I've updated so that all messages now go to the log, the bit I'm confused on is how I should be sending the messages.  I'm sending a plan text message: "<0x0a>D345003D"SIA-DCS"0001L0#5504[5004|Nri1HA1][Nri1HA1]_17:53:48,00-31-2019<0x0D>"

That is getting converted to a buffer, so I'm confused as to how line: 509 is supposed to work, "if (data && data[0] == 0x0a && data[len] == 0x0d)'  As data[0] is in buffer and reflects: 10 in my use case.

**Comment by schmupu** [comment]
I will take a look. Can you send me your message in a file as attachment?

**Comment by schmupu** [comment]
The SIA protocol is confusing. You can find an emulator [here](http://s545463982.onlinehome.us/DC09Gen/) and the SIA specification [here](https://www.yumpu.com/en/document/read/47594214/dc-09-preparing-for-ansi-public-review-security-industry-).
Every SIA message starts with LF and ends with CR in binary value (0x0A and 0x0D).
The CRC is calculated in HEX and saved as 2 bytes. For example the CRC == D345 than it saved as 0xD345 . 
In your example it shall looks like this (bold):

<0x0A>**<0xD345>**003D"SIA-DCS"0001L0#5504[5004|Nri1HA1][Nri1HA1]_17:53:48,00-31-2019<0x0D>

I hope I could help?

**Comment by schmupu** [comment]
could you please try it again. In version 1.0.1 I did an update. Maybe it helped

**Comment by schmupu** [comment]
fixed the error in Version 1.0.1. Unfortunately the alarm systems send the CRC in two different ways:

- 0xABCD (like Lupusec alarm system)
- ABCD (like your systems does)

the version 1.0.1 can handle both version.
Please test the version and give me a feedback.

**Comment by skitzo2000** [comment]
Thanks thorsten.  I will have an opportunity to test very soon.
