### ISSUE TITLE
UDP port Support

### ISSUE THREAD

**Issue by mrc1973** [schmupu/ioBroker.sia#8]
can you please add UDP support as my alarm can only communicate in this format

Thanks

**Comment by schmupu** [comment]
Hello,
should be no problem, but you have to test for me. I have no chance to change may Alam system to Udo

**Comment by mrc1973** [comment]
yeah i don't mind testing, i'm trying to get it to work with a jablotron alarm system which only has UDP support with SIA IP.

Ive seen the signals come through with wireshark but iobroker.sia doesn't see it at all.

**Comment by schmupu** [comment]
You can start testing the version 1.0.2 with UDP support. 
For installing the version 1.0.2 you have to go to the adapter tab. On the adapter tab, click on the github cat and choose the sia adapter. After installing, please start the sia instance again.

**Comment by schmupu** [comment]
@mrc1973 , did you had time to test the new version with UDP support?

**Comment by mrc1973** [comment]
yes its working now, thanks for that
